In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd 

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [ ]:
# Load the dataset into a pandas dataframe
df = pd.read_csv("../insurance.csv")

oure features are :[[19.   27.9   0.  ]
 [18.   33.77  1.  ]
 [28.   33.    3.  ]
 ...
 [18.   36.85  0.  ]
 [21.   25.8   0.  ]
 [61.   29.07  0.  ]]
<============================>
oure target values are :[[16884.924 ]
 [ 1725.5523]
 [ 4449.462 ]
 ...
 [ 1629.8335]
 [ 2007.945 ]
 [29141.3603]]


In [ ]:
# Select the input features (age, bmi, children) as X (independent variables)
x_train = df[['age','bmi','children']].values

# Select the target variable (charges) as Y (dependent variable)
y_train = df[['charges']].values


mean_x: [39.20702541 30.66339686  1.09491779]
std_x: [14.04470904  6.09590764  1.20504217]
[[-1.43876426 -0.45332    -0.90861367]
 [-1.50996545  0.5096211  -0.07876719]
 [-0.79795355  0.38330685  1.58092576]
 ...
 [-1.50996545  1.0148781  -0.90861367]
 [-1.29636188 -0.79781341 -0.90861367]
 [ 1.55168573 -0.26138796 -0.90861367]]


In [ ]:

# Compute the mean of each feature (column-wise mean)
mean_x = np.mean(x_train, axis=0)

# Compute the standard deviation of each feature (column-wise std)
std_x = np.std(x_train, axis=0)

1338
[158.16857294 -23.13879597 -87.86136674]


In [ ]:
# Normalize the features so they are on the same scale
# x_norm = (x - mean) / std for each feature
x_norm = (x_train - mean_x) / std_x

'\ndefining the cost ie j(w) = sum(y-hat[i] - y[i])**2\n'

In [ ]:
# Get number of training examples (m) and number of features (n)
m, n = x_norm.shape   # m = rows (examples), n = columns (features)

In [ ]:
# Initialize weight vector (w) with zeros (one weight for each feature)
w = np.zeros(n)

# Initialize bias (b) with zero
b = 0.0


SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (57287.py, line 9)

In [ ]:
# ---------------- COST FUNCTION ----------------
def compute_cost(x, y, w, b):
    """
    Compute the cost (mean squared error) for linear regression
    """
    m = x.shape[0]                   # number of training examples
    y_hat = x.dot(w) + b             # prediction for all examples, shape (m,)
    cost = (1/(2*m)) * np.sum((y_hat - y.flatten())**2)   # mean squared error
    return cost


In [ ]:
# ---------------- GRADIENT FUNCTION ----------------
def compute_gradient(x, y, w, b):
    """
    Compute the gradient of the cost function with respect to w and b
    """
    m = x.shape[0]                   # number of training examples
    y_hat = x.dot(w) + b             # prediction for all examples
    error = y_hat - y.flatten()      # difference between predictions and actual values
    
    # derivative with respect to weights
    dj_dw = (1/m) * (x.T.dot(error)) # gradient for each weight
    
    # derivative with respect to bias
    dj_db = (1/m) * np.sum(error)    # gradient for bias
    
    return dj_dw, dj_db


In [ ]:
# ---------------- GRADIENT DESCENT ----------------
alpha = 0.01        # learning rate
num_iters = 1000    # number of iterations for gradient descent

# Run gradient descent
for i in range(num_iters):
    # Compute gradients
    dj_dw, dj_db = compute_gradient(x_norm, y_train, w, b)
    
    # Update weights and bias
    w -= alpha * dj_dw
    b -= alpha * dj_db
    
    # Print cost every 100 iterations
    if i % 100 == 0:
        print(f"Iteration {i}: Cost = {compute_cost(x_norm, y_train, w, b)}")


In [ ]:
# Print final learned parameters
print("Final weights:", w)
print("Final bias:", b)